import requests
import json
import time
import zipfile

# options = {
#     "conversion_formats": {"docx": True, "tex.zip": True},
#     "math_inline_delimiters": ["$", "$"],
#     "rm_spaces": True
# }

headers = {
  "app_key": "APP_KEY",
  "app_id": "APP_ID"
}
r = requests.post("https://api.mathpix.com/v3/pdf",
    headers=headers,
    # data={
    #     "options_json": json.dumps(options)
    # },
    files={
        "file": open("sample.pdf","rb")
    }
)
# print(r.text.encode("utf8"))

if r.status_code == 200:
    print("Success! Response Data:")
    print(json.dumps(r.json(), indent=4))
else:
    print(f"Error: {r.status_code}")
    print(r.text)

json_data = json.loads(json.dumps(r.json())) if r and r.status_code == 200 else None
pdf_id = json_data['pdf_id'] #get pdf id from response

# Get results from same endpoint with pdf_id
# query endpoint until it returns complete:
conversion_response = None
while (True):
    time.sleep(5)
    conversion_response = requests.get("https://api.mathpix.com/v3/converter/"+pdf_id,
    headers=headers)
    json_data = json.loads(json.dumps(conversion_response.json()))
    
    if(json_data['status'] == "completed"):
        break

if conversion_response.status_code == 200:
    print("Success! Response Data:")
    print(json.dumps(conversion_response.json(), indent=4))
else:
    print(f"Error: {conversion_response.status_code}")
    print(conversion_response.text)


# get tex.zip file
url = "https://api.mathpix.com/v3/pdf/" + pdf_id + ".tex"
response = requests.get(url, headers=headers)
with open(pdf_id + ".tex.zip", "wb") as f:
    f.write(response.content)

# extract zip folder to current directory
with zipfile.ZipFile(pdf_id+".tex.zip","r") as zip_ref:
    zip_ref.extractall()

# The questions for query are: 
# 13) Use the method of cylindrical shells to find the volume generated by rotating the region bounded by the given curves about the y-axis: y= sqrt(5_x^2), y=0, x=0, x=2
# 15) Use the method of cylindrical shells to find the volume of the solid obtained by rotating the region bounded by the given curves about the x-axis: xy=1, x=0, y=1, y=3
# 17) Use the method of cylindrical shells to find the volume of the solid obtained by rotating the region bounded by the given curves about the x-axis: y=x^(3/2), y=8, x=0