# Generated by Django 5.1.6 on 2025-02-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbook', models.TextField(max_length=200)),
                ('chapter', models.IntegerField()),
                ('question_number', models.IntegerField()),
                ('question_text', models.CharField(max_length=200)),
                ('ai_response', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('transcription', models.TextField()),
                ('pdf_id', models.TextField()),
            ],
        ),
    ]
